<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Raden Roro Aura Putri Indira">
<meta name="dcterms.date" content="2024-01-11">

<title>Hubungan Antara Angka Melek Huruf Penduduk Terhadap Kemiskinan Tahun 2020</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="index.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Hubungan Antara Angka Melek Huruf Penduduk Terhadap Kemiskinan Tahun 2020</h1>
<p class="subtitle lead">Metode Penelitian Politeknik APP Jakarta</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Raden Roro Aura Putri Indira </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">January 11, 2024</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<p><img src="poltekapp.jpg" class="img-fluid"></p>
<section id="pendahuluan" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="pendahuluan"><span class="header-section-number">1</span> Pendahuluan</h2>
<section id="latar-belakang" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="latar-belakang"><span class="header-section-number">1.1</span> Latar belakang</h3>
<p>Masalah kemiskinan adalah salah satu isu yang kompleks dan mendalam dalam pembangunan sosial dan ekonomi suatu negara. Kemiskinan tidak hanya berkaitan dengan kurangnya sumber daya material, tetapi juga memiliki dampak yang luas terhadap aspek sosial, kesehatan, pendidikan, dan kualitas hidup masyarakat. Untuk mengatasi masalah kemiskinan, penting untuk memahami faktor-faktor yang mempengaruhinya.</p>
<p>Salah satu faktor yang diketahui memiliki keterkaitan erat dengan kemiskinan adalah tingkat melek huruf penduduk. Angka melek huruf penduduk menggambarkan tingkat literasi dan pendidikan masyarakat. Tingkat melek huruf yang rendah dapat menghambat akses masyarakat terhadap peluang ekonomi, pekerjaan yang layak, dan keahlian yang diperlukan dalam era globalisasi dan kemajuan teknologi.</p>
<p>Kondisi yang dirasakan Indonesia, berdasarkan data yang ada menunjukkan terjadi tren peningkatan kasus positif baru Covid-19 di Indonesia. Hal tersebut terjadi pada saat awal terjadi pandemi Covid-19 di Indonesia tanggal 2 Maret 2020 sampai dengan terjadi lonjakan peningkatan kasus baru hingga 25 Juli 2021. Bahkan lonjakan paling tinggi kasus positif baru Covid-19 di Indonesia terjadi pada saat tanggal 15 Juli 2021.Pandemi ini telah berdampak signifikan pada berbagai aspek kehidupan, termasuk pada tingkat kemiskinan dan melek huruf penduduk. Pembatasan sosial, penutupan sekolah, dan penurunan aktivitas ekonomi telah mempengaruhi pendidikan dan kesempatan ekonomi masyarakat.</p>
<p>Dalam konteks ini, penting untuk melakukan analisis yang mendalam tentang hubungan antara angka melek huruf penduduk dengan tingkat kemiskinan pada tahun 2020. Analisis ini akan memberikan pemahaman yang lebih baik tentang bagaimana tingkat literasi dan pendidikan dapat mempengaruhi tingkat kemiskinan di tengah krisis global seperti pandemi COVID-19.</p>
<p>Studi sebelumnya telah menunjukkan bahwa tingkat melek huruf yang tinggi dapat berkontribusi pada peningkatan kualitas hidup dan potensi ekonomi masyarakat. Masyarakat yang melek huruf memiliki pengetahuan dan keterampilan yang lebih baik untuk berpartisipasi dalam sektor formal ekonomi, mengakses informasi dan layanan publik, serta mengembangkan usaha mikro dan kecil. Oleh karena itu, meningkatkan angka melek huruf penduduk dapat menjadi strategi penting dalam mengurangi tingkat kemiskinan.</p>
<p>Namun, dalam realitas yang kompleks, hubungan antara angka melek huruf penduduk dengan kemiskinan tidaklah sederhana. Faktor-faktor lain, seperti kesenjangan pendapatan, akses terhadap pekerjaan yang layak, dan kebijakan pemerintah juga berperan dalam menentukan tingkat kemiskinan. Oleh karena itu, diperlukan analisis yang komprehensif dan metode penelitian yang tepat untuk memahami hubungan ini secara lebih baik.</p>
<p>Melalui penelitian yang mendalam tentang hubungan antara angka melek huruf penduduk dengan kemiskinan tahun 2020, diharapkan dapat memberikan pemahaman yang lebih baik tentang dinamika dan faktor-faktor yang mempengaruhi kemiskinan dalam konteks yang khusus. Temuan penelitian ini dapat berkontribusi pada pengembangan kebijakan dan program yang lebih efektif dalam upaya mengurangi kemiskinan dan meningkatkan literasi penduduk.</p>
</section>
<section id="ruang-lingkup" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="ruang-lingkup"><span class="header-section-number">1.2</span> Ruang lingkup</h3>
<p>Ruang lingkup pembahasan dalam penelitian ini akan difokuskan pada variabel yang relevan untuk analisis, yakni hubungan antara Angka Melek Huruf Penduduk dan Tingkat Kemiskinan pada tahun 2020. Batasan masalah ini memiliki peran penting dalam mengidentifikasi isu-isu yang akan dibahas dan membatasi cakupan dari proses penelitian yang dilakukan.</p>
</section>
<section id="rumusan-masalah" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="rumusan-masalah"><span class="header-section-number">1.3</span> Rumusan masalah</h3>
<p>1.Bagaimana hubungan antara Angka Melek Huruf Penduduk dengan tingkat kemiskinan pada tahun 2020? 2.Apa dampak pandemi COVID-19 terhadap Angka Melek Huruf Penduduk dan bagaimana dampak tersebut mempengaruhi tingkat kemiskinan?</p>
</section>
<section id="tujuan-dan-manfaat-penelitian" class="level3" data-number="1.4">
<h3 data-number="1.4" class="anchored" data-anchor-id="tujuan-dan-manfaat-penelitian"><span class="header-section-number">1.4</span> Tujuan dan manfaat penelitian</h3>
<p>Penelitian ini bertujuan menganalisis hubungan Angka Melek Huruf Penduduk dengan tingkat kemiskinan tahun 2020, terutama dalam konteks dampak pandemi COVID-19. Fokus penelitian juga mencakup pemahaman peran literasi dalam mengatasi tantangan ekonomi pasca-pandemi, mengeksplorasi variabilitas hubungan antardaerah, dan mengidentifikasi faktor-faktor modifikasi. Manfaatnya melibatkan kontribusi teoritis, informasi praktis untuk pembuat kebijakan, dan dasar bagi pengembangan program intervensi pendidikan dan ekonomi. Penelitian ini khususnya memberikan wawasan mendalam tentang dampak pandemi pada literasi dan kemiskinan, serta memungkinkan perbandingan regional untuk adaptasi kebijakan yang sesuai dengan karakteristik wilayah.</p>
</section>
<section id="package" class="level3" data-number="1.5">
<h3 data-number="1.5" class="anchored" data-anchor-id="package"><span class="header-section-number">1.5</span> Package</h3>
<p>Ini tidak wajib ada di tulisan anda tapi anda dapat menunjukkan Packages yang digunakan antara lain sebagai berikut:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2) </span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="studi-pustaka" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="studi-pustaka"><span class="header-section-number">2</span> Studi pustaka</h2>
<p>Menurut Hall dan Midgley pengertian kemiskinan adalah kondisi deprivasi materi dan sosial yang menyebabkan individu hidup di bawah standar kehidupan yang layak, atau kondisi di mana individu mengalami deprivasi relatif dibandingkan dengan individu yang lainnya dalam masyarakat.</p>
</section>
<section id="metode-penelitian" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="metode-penelitian"><span class="header-section-number">3</span> Metode penelitian</h2>
<section id="data" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="data"><span class="header-section-number">3.1</span> Data</h3>
<p>Data yang saya gunakan berupa Angka Melek Huruf dan provinsi terkait</p>
<p>dan juga Data Jumlah Penduduk Miskin di provinsi yang terkait</p>
<table class="table">
<thead>
<tr class="header">
<th>Provinsi</th>
<th>Angka Melek Huruf</th>
<th>Angka Kemiskinan</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ACEH</td>
<td>99.98</td>
<td>15.43</td>
</tr>
<tr class="even">
<td>SUMATERA UTARA</td>
<td>99.9</td>
<td>9.14</td>
</tr>
<tr class="odd">
<td>SUMATERA BARAT</td>
<td>99.88</td>
<td>6.56</td>
</tr>
<tr class="even">
<td>RIAU</td>
<td>99.94</td>
<td>7.04</td>
</tr>
<tr class="odd">
<td>JAMBI</td>
<td>99.92</td>
<td>7.97</td>
</tr>
<tr class="even">
<td>SUMATERA SELATAN</td>
<td>99.94</td>
<td>12.98</td>
</tr>
<tr class="odd">
<td>BENGKULU</td>
<td>99.93</td>
<td>15.30</td>
</tr>
<tr class="even">
<td>LAMPUNG</td>
<td>99.89</td>
<td>12.76</td>
</tr>
<tr class="odd">
<td>KEP.BANGKA BELITUNG</td>
<td>99.87</td>
<td>4.89</td>
</tr>
<tr class="even">
<td>KEP.RIAU</td>
<td>99.91</td>
<td>6.13</td>
</tr>
<tr class="odd">
<td>DKI JAKARTA</td>
<td>99.96</td>
<td>4.69</td>
</tr>
<tr class="even">
<td>JAWA BARAT</td>
<td>99.97</td>
<td>8.43</td>
</tr>
<tr class="odd">
<td>JAWA TENGAH</td>
<td>99.95</td>
<td>11.84</td>
</tr>
<tr class="even">
<td>DI YOGYAKARTA</td>
<td>99.93</td>
<td>12.80</td>
</tr>
<tr class="odd">
<td>JAWA TIMUR</td>
<td>99.94</td>
<td>11.46</td>
</tr>
<tr class="even">
<td>BANTEN</td>
<td>99.94</td>
<td>6.63</td>
</tr>
<tr class="odd">
<td>BALI</td>
<td>99.94</td>
<td>4.45</td>
</tr>
<tr class="even">
<td>NUSA TENGGARA BARAT</td>
<td>99.93</td>
<td>14.23</td>
</tr>
<tr class="odd">
<td>NUSA TENGGARA TIMUR</td>
<td>98.89</td>
<td>21.21</td>
</tr>
<tr class="even">
<td>KALIMANTAN BARAT</td>
<td>99.86</td>
<td>7.24</td>
</tr>
<tr class="odd">
<td>KALIMANTAN TENGAH</td>
<td>99.86</td>
<td>5.26</td>
</tr>
<tr class="even">
<td>KALIMANTAN SELATAN</td>
<td>99.92</td>
<td>4.83</td>
</tr>
<tr class="odd">
<td>KALIMANTAN TIMUR</td>
<td>99.96</td>
<td>6.64</td>
</tr>
<tr class="even">
<td>KALIMANTAN UTARA</td>
<td>99.6</td>
<td>7.41</td>
</tr>
<tr class="odd">
<td>SULAWESI UTARA</td>
<td>99.92</td>
<td>7.78</td>
</tr>
<tr class="even">
<td>SULAWESI TENGAH</td>
<td>99.8</td>
<td>13.06</td>
</tr>
<tr class="odd">
<td>SULAWESI SELATAN</td>
<td>99.73</td>
<td>8.99</td>
</tr>
<tr class="even">
<td>SULAWESI TENGGARA</td>
<td>99.93</td>
<td>11.69</td>
</tr>
<tr class="odd">
<td>GORONTALO</td>
<td>99.87</td>
<td>15.59</td>
</tr>
<tr class="even">
<td>SULAWESI BARAT</td>
<td>99.47</td>
<td>11.50</td>
</tr>
<tr class="odd">
<td>MALUKU</td>
<td>99.9</td>
<td>17.99</td>
</tr>
<tr class="even">
<td>MALUKU UTARA</td>
<td>99.95</td>
<td>6.97</td>
</tr>
<tr class="odd">
<td>PAPUA BARAT</td>
<td>99.52</td>
<td>21.70</td>
</tr>
<tr class="even">
<td>PAPUA</td>
<td>90.78</td>
<td>26.80</td>
</tr>
</tbody>
</table>
<p><img src="logowa.jpg" class="img-fluid"></p>
<p>penelitian ini menggunakan data yang bersumber dari Badan Pusat Statistik (BPS)</p>
<p>Baca Data</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"melekhuruf.xlsx"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
      x y    
  &lt;dbl&gt; &lt;chr&gt;
1 100.  15.43
2  99.9 9.14 
3  99.9 6.56 
4  99.9 7.04 
5  99.9 7.97 
6  99.9 12.98</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggplot2"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"dplyr"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>dat,<span class="fu">aes</span>(<span class="at">x=</span>x,<span class="at">y=</span>y))<span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color=</span><span class="st">"blue"</span>,<span class="at">size=</span><span class="dv">2</span>)<span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Tabel 1 Hubungan Antara Angka Melek Huruf Penduduk TerhadaP Kemiskinan Tahun 2020"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x=</span><span class="st">"Angka Melek Huruf"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">y=</span><span class="st">"Kemiskinan"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption=</span><span class="st">"sumber:Badan Pusat Statistik"</span>)<span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="metode-analisis" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="metode-analisis"><span class="header-section-number">3.2</span> Metode Analisis</h3>
<p>Metode yang dipilih adalah regresi univariat atau Ordinary Least Square (OLS) dengan 1 variabel independen. Penelitian ini bermaksud mencari hubungan antara Angka Melek Huruf dan Kemiskinan. Spesifikasi yang dilakukan adalah:</p>
<p><span class="math display">\[
y_{t}=\beta_0 + \beta_1 x_t+\mu_t\]</span> di mana <span class="math inline">\(y_t\)</span> adalah kemiskinan dan <span class="math inline">\(x_t\)</span> adalah angka melek huruf.</p>
</section>
</section>
<section id="pembahasan" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="pembahasan"><span class="header-section-number">4</span> Pembahasan</h2>
<section id="pembahasan-masalah" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pembahasan-masalah"><span class="header-section-number">4.1</span> Pembahasan masalah</h3>
<p>Dikarenakan saya menggunakan OLS, Pembahasan saya disini hanya menghubungkan Angka Melek Huruf dan kemiskinan. Data tersebut saya satukan untuk saya regresi dan tampilannya seperti ini.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"readxl"</span>)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>dat<span class="ot">&lt;-</span><span class="fu">read_excel</span>(<span class="st">"melekhuruf.xlsx"</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
      x y    
  &lt;dbl&gt; &lt;chr&gt;
1 100.  15.43
2  99.9 9.14 
3  99.9 6.56 
4  99.9 7.04 
5  99.9 7.97 
6  99.9 12.98</code></pre>
</div>
</div>
</section>
<section id="analisis-masalah" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="analisis-masalah"><span class="header-section-number">4.2</span> Analisis masalah</h3>
<p>Hasil regresinya adalah</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>reg1<span class="ot">&lt;-</span><span class="fu">lm</span>(y<span class="sc">~</span>x,<span class="at">data=</span>dat)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(reg1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = y ~ x, data = dat)

Residuals:
   Min     1Q Median     3Q    Max 
-5.643 -3.398 -1.444  2.690 10.778 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 207.3227    49.8422   4.160 0.000223 ***
x            -1.9735     0.5005  -3.943 0.000411 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 4.509 on 32 degrees of freedom
Multiple R-squared:  0.327, Adjusted R-squared:  0.306 
F-statistic: 15.55 on 1 and 32 DF,  p-value: 0.0004107</code></pre>
</div>
</div>
</section>
</section>
<section id="kesimpulan" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="kesimpulan"><span class="header-section-number">5</span> Kesimpulan</h2>
<p>Model regresi menegaskan hubungan signifikan antara angka melek huruf penduduk (x) dan tingkat kemiskinan (y) pada tahun 2020. Dengan ŷ=207.3227−1.9735<span class="math inline">\(x\)</span>, setiap kenaikan satu unit dalam angka melek huruf penduduk menyebabkan penurunan rata-rata 1.9735 unit dalam tingkat kemiskinan. Koefisien estimasi yang signifikan dan p-value rendah pada F-statistic (15.55, p-value: 0.0004107) menunjukkan bahwa model secara keseluruhan memberikan kontribusi yang berarti dalam menjelaskan variasi dalam tingkat kemiskinan.</p>
</section>
<section id="referensi" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="referensi"><span class="header-section-number">6</span> Referensi</h2>
<p>BPS Provinsi Jawa Timur. (t.t.). Diambil 11 Januari 2024, dari https://jatim.bps.go.id/indicator/23/344/2/persentase-penduduk-miskin-menurut-provinsi-.html</p>
<p>Di Tengah Pandemi, Angka Kemiskinan Meninggi | Indonesia Baik. (t.t.). Diambil 11 Januari 2024, dari https://indonesiabaik.id/infografis/di-tengah-pandemi-angka-kemiskinan-meninggi</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>